# Site settings
title: 2020 SoCal Robotics Symposium

url: http://scr2020.ucla.edu/
baseurl: ''

conference_title: "Southern California Robotics Symposium"
conference_title_short: "SCR"
year: "2020"
infoline_text: "In light of recent events surrounding the COVID-19 outbreak, SCR2020 will be postponed until further notice. We will provide more information when we have new logistical details, and we thank you for your understanding and patience as we navigate this complex situation."

# Color settings
color:
  primary-dark: '#2774AE' # UCLA Primary Blue
  title: '#ebf0f4'
  links: '#8BB8E8' # UCLA Lighter Blue
  accent: '#FFD100' # UCLA Primary Gold

# conference data
background-image: img/royce_night.jpg
directions-link: https://goo.gl/maps/CtCxUAHPBMjXnKbu9
map-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1652.505897809897!2d-118.44563254873435!3d34.06921187954675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc88bcefb20f%3A0xc622b89fcd2f5d21!2sEngineering%20VI!5e0!3m2!1sen!2sus!4v1580595924658!5m2!1sen!2sus
organizer-email : scr2020@ucla.edu
registration-page : 
upload-form: 

collections:
  - invited_speakers
  - organizers
  - sessions
  - papers
  - advisors

# Build settings
markdown: kramdown
permalink: pretty
