# Site settings
title: 2022 SoCal Robotics Symposium

url: http://scr.ucla.edu/
baseurl: ''

conference_title: "Southern California Robotics Symposium"
conference_title_short: "SCR"
year: "2022"
<<<<<<< HEAD
infoline_text: "We are at capacity for this year, unfortunately walk-ins will not be accommodated"
=======
infoline_text: ""
>>>>>>> a27071d81ea8979e73e5ce7e29d27d74536156fd

# Color settings
color:
  primary-dark: '#2774AE' # UCLA Primary Blue
  title: '#ebf0f4'
  links: '#8BB8E8' # UCLA Lighter Blue
  accent: '#FFD100' # UCLA Primary Gold

# conference data
background-image: img/royce_night.jpg
directions-link: https://goo.gl/maps/uT2oq7DQBNVPbykGA
map-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3305.0003991961744!2d-118.44671428491472!3d34.06950402426793!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc88bcefb20f%3A0xc622b89fcd2f5d21!2sEngineering%20VI!5e0!3m2!1sen!2sus!4v1661494131499!5m2!1sen!2sus
organizer-email : scr2022@ucla.edu
registration-page : https://commerce.cashnet.com/UCLASCR 
upload-form: 

collections:
  - invited_speakers
  - organizers
  - sessions
  - papers
  - advisors

# Build settings
markdown: kramdown
permalink: pretty
